apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-nginx-conf" ( include "sace.fullname" . ) }}
  labels:
    {{- include "sace.labels" . | nindent 4 }}
data:  
  sace-bacias.conf: {{ tpl (.Files.Get "files/nginx/conf/sace-bacias.conf") . | indent 4 | quote }}
  {{- if .Values.geoserver.enabled }}
  sace-geoserver.conf: {{ tpl (.Files.Get "files/nginx/conf/sace-geoserver.conf") . | indent 4 | quote }}
  {{- end }}
  sace-resources.conf: {{ tpl (.Files.Get "files/nginx/conf/sace-resources.conf") . | indent 4 | quote }}
