apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.overrides.default.name | default (printf "%s-nginx-default-conf" ( include "sace.fullname" . )) }}
  labels:
    {{- include "sace.labels" . | nindent 4 }}
data:
  default.conf: {{ tpl (.Files.Get "files/conf/default.conf") . | indent 4 | quote }}