apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sace.fullname" . }}-nginx-default-conf
  labels:
    {{- include "sace.labels" . | nindent 4 }}
data:
  default.conf: {{ tpl (.Files.Get "files/conf/default.conf") . | indent 4 | quote }}
