apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-nginx-html" ( include "sace.fullname" . ) }}
  labels:
    {{- include "sace.labels" . | nindent 4 }}
data:
  index.html: {{ tpl (.Files.Get "files/nginx/html/index.html") . | indent 4 | quote }}
  50x.html: {{ tpl (.Files.Get "files/nginx/html/50x.html") . | indent 4 | quote }}
  404.html: {{ tpl (.Files.Get "files/nginx/html/404.html") . | indent 4 | quote }}
