config:
  basins:
    - name: branco
      title: Bacia do Branco
      # url: http://sace.sgb-sace-homolog.apps-crc.testing/branco
      imageDir: /mnt/sace/data
      bounds:
        minX: -65
        minY: -2
        maxX: -59
        maxY: 6
      enableScheduling: false
      enableRetrieve: false
      db:
        url: jdbc:postgresql://sace-postgresql.sgb-sace-homolog.svc.cluster.local:5432/sace_branco
      geoserver:
        workspace: BRANCO
        url: http://sace.sgb-sace-homolog.apps-crc.testing/geoserver
      overrideValues:
        # replicaCount: 2
        # autoscaling:
        #   enabled: true
        pvc:
          # className: thin-csi
          storage:
            size: 1Gi

    - name: araguaia
      title: Bacia do Araguaia
      # url: http://sace.sgb-sace-homolog.apps-crc.testing/araguaia
      imageDir: /mnt/sace/data
      bounds:
        minX: -65
        minY: -2
        maxX: -59
        maxY: 6
      db:
        url: jdbc:postgresql://sace-postgresql.sgb-sace-homolog.svc.cluster.local:5432/sace_araguaia
      geoserver:
        workspace: ARAGUAIA
        url: http://sace.sgb-sace-homolog.apps-crc.testing/geoserver
      overrideValues:
        # replicaCount: 2
        # autoscaling:
        #   enabled: true
        pvc:
          # className: thin-csi
          storage:
            size: 10Gi
  selectedBasins:
    - branco
    - araguaia

image:
  repository: docker.io/cmotadev/sace
  tag: testing4
  pullPolicy: Always

pvc:
  enabled: true
  keep: false
  storage:
    className: "crc-csi-hostpath-provisioner"
    size: 5Gi

replicaCount: 1

reverseProxy:
  enabled: false  

geoserver:
  enabled: true
  config:
    cors:
      allowedOrigins:
        - '*'
    csrf:
      disabled: true
    proxyBaseURL: 'http://sace.sgb-sace-homolog.apps-crc.testing/geoserver'
  image:
    tag: 2.24.4
  imagePullPolicy: Always

postgresql: 
  enabled: true
  auth:
    username: "sace"
    password: "sace"
    database: "sace"
    postgresPassword: "postgres"
  primary:
    extendedConfiguration: |-
      log_statement = all
      log_directory = 'logs'                  # directory where log files are written,
      log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'        # log file name pattern,
      log_file_mode = 0660 

nginx:
  ingress:
    enabled: true
    hosts:
      - host: sace.sgb-sace-homolog.apps-crc.testing
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: nginx-unprivileged-tls
    #    hosts:
    #      - nginx-unprivileged.apps-crc.testing
  overrides:
    default: 
      name: foo
    html: 
      name: bar