{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins }}
{{- $_saceProps := mergeOverwrite (deepCopy $saceDefault) $item -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (printf "%s-%s" $saceName $_saceProps.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceProps.name }}
data:
  SACE_CONTEXT: {{ $_saceProps.name | quote }}
  JAVA_XMX: {{ $_saceProps.jvm.xmx | quote }}
  JAVA_XMS: {{ $_saceProps.jvm.xms | quote }}
  workspaceGeoserver: {{ $_saceProps.geoserver.workspace | quote }}
  urlGeoserver: {{ $_saceProps.geoserver.url | quote }}
  {{- $bounds := $_saceProps.bounds }}
  boundMap: {{ printf "new OpenLayers.Bounds(%f, %f, %f, %f)" $bounds.minX $bounds.minY $bounds.maxX $bounds.maxY | quote }}
  ativarAgendamentos: {{ $_saceProps.enableScheduling | quote }}
  ativarRecuperacoes: {{ $_saceProps.enableRetrieve | quote }}
  nomeSistema: {{ $_saceProps.title | quote }}
  imageDir: {{ $_saceProps.imageDir | quote }}
  {{- $url := printf "%s/%s" (include "sace.urlTemplate" $) $_saceProps.name }}
  urlSistema: {{ $_saceProps.url | default $url | quote }}
immutable: false
{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}
