{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins }}
{{- $_saceName := (printf "%s-%s" $saceName $item.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $item.name }}
data:
  SACE_CONTEXT: {{ $item.name | quote }}
  {{- $jvm := $item.jvm | default dict }}
  JAVA_XMX: {{ hasKey $jvm "xmx" | ternary $jvm.xmx $saceDefault.jvm.xmx | quote }}
  JAVA_XMS: {{ hasKey $jvm "xms" | ternary $jvm.xms $saceDefault.jvm.xms | quote }}
  {{- $geoserver := $item.geoserver | default dict }}
  workspaceGeoserver: {{ hasKey $geoserver "workspace" | ternary $geoserver.workspace $saceDefault.geoserver.workspace | quote }}
  urlGeoserver: {{ hasKey $geoserver "url" | ternary $geoserver.url $saceDefault.geoserver.url | quote }}
  {{- $bounds := $item.bounds | default $saceDefault.bounds }}
  boundMap: {{ printf "new OpenLayers.Bounds(%f, %f, %f, %f)" $bounds.minX $bounds.minY $bounds.maxX $bounds.maxY | quote }}
  ativarAgendamentos: {{ $item.enableScheduling | default $saceDefault.enableScheduling | quote }}
  ativarRecuperacoes: {{ $item.enableRetrieve | default $saceDefault.enableRetrieve | quote }}
  nomeSistema: {{ $item.title | default $saceDefault.title | quote }}
  imageDir: {{ $item.imageDir | default $saceDefault.imageDir | quote }}
  {{- $url := printf "%s/%s" (include "sace.urlTemplate" $) $item.name }}
  urlSistema: {{ $item.url | default $url | quote }}
immutable: false
{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}
