{{- $saceServiceAccount := (include "sace.serviceAccountName" .) -}}
{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}
{{- $saceSelectorLabels := (include "sace.selectorLabels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins -}}
{{- $_saceProps := mergeOverwrite (deepCopy $saceDefault) $item -}}
{{- $_overrideValues := (hasKey $_saceProps "overrideValues" | ternary $_saceProps.overrideValues dict) -}}

{{- $_saceName := (printf "%s-%s" $saceName $_saceProps.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceProps.name }}
spec:
  {{- if not (hasKey $_overrideValues "autoscaling") -}}{{- $_ := set $_overrideValues "autoscaling" dict -}}{{- end -}}
  {{- $_hpa := mergeOverwrite (deepCopy $.Values.autoscaling) $_overrideValues.autoscaling -}}
  {{- if not $_hpa.enabled }}
  {{- $_replicaCount := (hasKey $_overrideValues "replicaCount" | ternary $_overrideValues.replicaCount $.Values.replicaCount) }}
  replicas: {{ $_replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- $saceSelectorLabels | nindent 6 }}
      sace.sgb.gov.br/bacia: {{ $_saceProps.name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if not (hasKey $_overrideValues "podAnnotations") -}}{{- $_ := set $_overrideValues "podAnnotations" dict -}}{{- end -}}
        {{- $_podAnnotations := mergeOverwrite (deepCopy $.Values.podAnnotations) $_overrideValues.podAnnotations -}}
        {{- with $_podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- $saceSelectorLabels | nindent 8 }}
        sace.sgb.gov.br/bacia: {{ $_saceProps.name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $saceServiceAccount }}
      {{- if not (hasKey $_overrideValues "podSecurityContext") -}}{{- $_ := set $_overrideValues "podSecurityContext" dict -}}{{- end -}}
      {{- $_podSecurityContext := mergeOverwrite (deepCopy $.Values.podSecurityContext) $_overrideValues.podSecurityContext -}}
      {{ with $_podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: sace-data
          persistentVolumeClaim:
            claimName: {{ $_saceName }}      
      {{- with .Values.extraHosts }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          {{- if not (hasKey $_overrideValues "securityContext") -}}{{- $_ := set $_overrideValues "securityContext" dict -}}{{- end -}}
          {{- $_securityContext := mergeOverwrite (deepCopy $.Values.securityContext) $_overrideValues.securityContext -}}
          {{ with $_securityContext }}
          securityContext:            
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ $_saceProps.name }}/
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: {{ $_saceProps.imageDir }}
              name: sace-data
          envFrom:
            - configMapRef:
                name: {{ $_saceName }}
            - secretRef:
                name: {{ $_saceName }}
          {{- if not (hasKey $_overrideValues "resources") -}}{{- $_ := set $_overrideValues "resources" dict -}}{{- end -}}
          {{- $_resources := mergeOverwrite (deepCopy $.Values.resources) $_overrideValues.resources -}}
          {{ with $_resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if not (hasKey $_overrideValues "nodeSelector") -}}{{- $_ := set $_overrideValues "nodeSelector" dict -}}{{- end -}}
      {{- $_nodeSelector := mergeOverwrite (deepCopy $.Values.nodeSelector) $_overrideValues.nodeSelector -}}
      {{- with $_nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not (hasKey $_overrideValues "affinity") -}}{{- $_ := set $_overrideValues "affinity" dict -}}{{- end -}}
      {{- $_affinity := mergeOverwrite (deepCopy $.Values.affinity) $_overrideValues.affinity -}}
      {{- with $_affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not (hasKey $_overrideValues "tolerations") -}}{{- $_ := set $_overrideValues "tolerations" list -}}{{- end -}}
      {{- $_tolerations := uniq (concat (deepCopy $.Values.tolerations) $_overrideValues.tolerations) -}}
      {{- with $_tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}