{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins -}}
{{- $_saceName := (printf "%s-%s" $saceName $item.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
{{- $_overrideValues := (hasKey $item "overrideValues" | ternary $item.overrideValues dict) -}}

{{- $_hpa := (hasKey $_overrideValues "autoscaling" | ternary $_overrideValues.autoscaling $.Values.autoscaling) -}}
{{- if $_hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $item.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $_saceName }}
  minReplicas: {{ $_hpa.minReplicas }}
  maxReplicas: {{ $_hpa.maxReplicas }}
  metrics:
    {{- if $_hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ $_hpa.targetCPUUtilizationPercentage }}
          type: Utilization
    {{- end }}
    {{- if $_hpa.targetMemoryUtilizationPercentage }}
     - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ $_hpa.targetMemoryUtilizationPercentage }}
          type: Utilization
    {{- end }}
{{- end }}

{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}