{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins -}}
{{- $_saceProps := mergeOverwrite (deepCopy $saceDefault) $item -}}
{{- $_overrideValues := (hasKey $_saceProps "overrideValues" | ternary $_saceProps.overrideValues dict) -}}

{{/* Get only hpa values */}}
{{- if not (hasKey $_overrideValues "autoscaling") -}}{{- $_ := set $_overrideValues "autoscaling" dict -}}{{- end -}}
{{- $_hpa := mergeOverwrite (deepCopy $.Values.autoscaling) $_overrideValues.autoscaling -}}

{{- if $_hpa.enabled -}}
{{- $_saceName := (printf "%s-%s" $saceName $_saceProps.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
{{- with $_hpa }}
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceProps.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $_saceName }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- if .targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ .targetCPUUtilizationPercentage }}
          type: Utilization
    {{- end }}
    {{- if .targetMemoryUtilizationPercentage }}
     - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .targetMemoryUtilizationPercentage }}
          type: Utilization
    {{- end }}
{{- end }}
{{- end }}

{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}