{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins -}}
{{- $_saceProps := mergeOverwrite (deepCopy $saceDefault) $item -}}
{{- $_overrideValues := (hasKey $_saceProps "overrideValues" | ternary $_saceProps.overrideValues dict) -}}

{{/* Get only pvc values */}}
{{- if not (hasKey $_overrideValues "pvc") -}}{{- $_ := set $_overrideValues "pvc" dict -}}{{- end -}}
{{- $_pvc := mergeOverwrite (deepCopy $.Values.pvc) $_overrideValues.pvc -}}

{{- if $_pvc.enabled -}}
{{- $_saceName := (printf "%s-%s" $saceName $item.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: PersistentVolumeClaim
{{- with $_pvc }}
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceProps.name }}
  {{- if .keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  volumeMode: Filesystem
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  accessModes:
    {{- range .storage.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .storage.className | quote }}
  resources:
    requests:
      storage: {{ .storage.size }}
{{- end }}
{{- end }}
{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}