{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins }}
{{- $_saceName := (printf "%s-%s" $saceName $item.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $_saceName }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $item.name }}
type: Opaque
stringData:
  JDBC_URL: {{ .db.url | default $saceDefault.db.url | quote }}
  POSTGRES_USER: {{ .db.user | default $saceDefault.db.user | quote }}
  POSTGRES_PASS: {{ .db.pass | default $saceDefault.db.pass | quote }}
{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}