{{- $saceName := (include "sace.fullname" .) -}}
{{- $saceLabels := (include "sace.labels" .) -}}

{{/* Basins */}}
{{- $saceDefault := .Values.config.default -}}
{{- $saceBasins := .Values.config.basins -}}
{{- $saceNumBasins := len $saceBasins -}}

{{/* set default, if basin is empty */}}
{{- if eq $saceNumBasins 0 -}}
{{- $saceBasins = list $saceDefault -}}
{{- $saceNumBasins = 1 -}}
{{- end -}}

{{- range $index, $item := $saceBasins }}
{{- $_saceProps := mergeOverwrite (deepCopy $saceDefault) $item -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ (printf "%s-%s" $saceName $_saceProps.name) | lower | replace " " "-" | replace "_" "-" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- $saceLabels | nindent 4 }}
    sace.sgb.gov.br/bacia: {{ $_saceProps.name }}
type: Opaque
stringData:
  JDBC_URL: {{ $_saceProps.db.url | quote }}
  POSTGRES_USER: {{ $_saceProps.db.user | quote }}
  POSTGRES_PASS: {{ $_saceProps.db.pass | quote }}
{{ if ne (add1 $index) $saceNumBasins -}}
---
{{- end -}}
{{- end -}}